In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor
import matplotlib.pyplot as plt
import seaborn as sns
import sys, os

In [2]:

# Load data 
scripts_path = os.path.abspath(os.path.join(os.getcwd(), '../Scripts'))
sys.path.append(scripts_path)
from paths import PATH_CLEAN_CSV
df= pd.read_csv(PATH_CLEAN_CSV)

In [3]:
# Data Preprocessing
def preprocess_data(df):
    # Convert time columns to datetime and extract features
    df['Order_Time'] = pd.to_datetime(df['Order_Time']).dt.hour
    df['Pickup_Time'] = pd.to_datetime(df['Pickup_Time']).dt.hour
    df['Order_Date'] = pd.to_datetime(df['Order_Date']).dt.dayofweek
    
    # Calculate distance using Haversine formula
    def haversine(lat1, lon1, lat2, lon2):
        lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
        dlat = lat2 - lat1 
        dlon = lon2 - lon1 
        a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
        c = 2 * np.arcsin(np.sqrt(a)) 
        km = 6371 * c
        return km
    
    df['Distance_km'] = df.apply(lambda x: haversine(
        x['Store_Latitude'], x['Store_Longitude'], 
        x['Drop_Latitude'], x['Drop_Longitude']), axis=1)
    
    # Drop unnecessary columns
    df = df.drop(['Order_ID', 'Store_Latitude', 'Store_Longitude', 
                 'Drop_Latitude', 'Drop_Longitude'], axis=1)
    
    # Clean categorical columns
    df['Traffic'] = df['Traffic'].str.strip()
    df['Vehicle'] = df['Vehicle'].str.strip()
    
    return df

In [4]:

# Preprocess the data
df_processed = preprocess_data(df)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_2076\2284031454.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Order_Time'] = pd.to_datetime(df['Order_Time']).dt.hour
C:\Users\Usuario\AppData\Local\Temp\ipykernel_2076\2284031454.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Pickup_Time'] = pd.to_datetime(df['Pickup_Time']).dt.hour

In [5]:

# Define features and target
X = df_processed.drop('Delivery_Time', axis=1)
y = df_processed['Delivery_Time']

In [6]:

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:

# Define categorical and numerical features
categorical_features = ['Weather', 'Traffic', 'Vehicle', 'Area', 'Category']
numerical_features = ['Agent_Age', 'Agent_Rating', 'Order_Date', 'Order_Time', 
                     'Pickup_Time', 'Distance_km']

In [8]:

# Create preprocessing pipelines
numeric_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)])

In [9]:

# Create and evaluate models
def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    
    print(f"Model Performance:")
    print(f"MSE: {mse:.2f}")
    print(f"RMSE: {rmse:.2f}")
    print(f"MAE: {mae:.2f}")
    print(f"R²: {r2:.2f}")
    
    # Plot feature importance for tree-based models
    if hasattr(model, 'feature_importances_'):
        feature_importance = model.feature_importances_
        feature_names = model[:-1].get_feature_names_out()
        
        plt.figure(figsize=(10, 6))
        sns.barplot(x=feature_importance, y=feature_names)
        plt.title('Feature Importance')
        plt.show()

In [22]:
data=df_processed

In [10]:

# Option 1: XGBoost with Hyperparameter Tuning
xgb_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', XGBRegressor(random_state=42, n_jobs=-1))])

xgb_params = {
    'regressor__n_estimators': [100, 200, 300],
    'regressor__max_depth': [3, 5, 7],
    'regressor__learning_rate': [0.01, 0.1, 0.2],
    'regressor__subsample': [0.8, 1.0],
    'regressor__colsample_bytree': [0.8, 1.0]
}

xgb_grid = GridSearchCV(xgb_pipeline, xgb_params, cv=5, 
                        scoring='neg_mean_squared_error', n_jobs=-1)
xgb_grid.fit(X_train, y_train)

best_xgb = xgb_grid.best_estimator_
print("\nXGBoost Best Parameters:", xgb_grid.best_params_)
evaluate_model(best_xgb, X_test, y_test)

XGBoost Best Parameters: {'regressor__colsample_bytree': 0.8, 'regressor__learning_rate': 0.1, 'regressor__max_depth': 7, 'regressor__n_estimators': 100, 'regressor__subsample': 1.0}
Model Performance:
MSE: 489.29
RMSE: 22.12
MAE: 17.11
R²: 0.82

In [ ]:
# Save the best model
import joblib
joblib.dump(best_xgb, 'delivery_time_predictor_xgb.pkl')

['delivery_time_predictor_xgb.pkl']

Save the data

In [12]:
save_path = os.path.abspath(os.path.join(os.getcwd(), '../data/prepared_data.csv'))
sys.path.append(save_path)

In [30]:
print(save_path)

c:\Users\Usuario\Downloads\Logistic_Analysis-main\data\prepared_data.csv

In [31]:
X.to_csv(save_path)

In [32]:
X

,Unnamed: 0,Agent_Age,Agent_Rating,Order_Date,Order_Time,Pickup_Time,Weather,Traffic,Vehicle,Area,Category,Distance_km
0,0,37,4.9,5,11,11,Sunny,High,motorcycle,Urban,Clothing,3.025149
1,1,34,4.5,4,19,19,Stormy,Jam,scooter,Metropolitian,Electronics,20.183530
2,2,23,4.4,5,8,8,Sandstorms,Low,motorcycle,Urban,Sports,1.552758
3,3,38,4.7,1,18,18,Sunny,Medium,motorcycle,Metropolitian,Cosmetics,7.790401
4,4,32,4.6,5,13,13,Cloudy,High,scooter,Metropolitian,Toys,6.210138
...,...,...,...,...,...,...,...,...,...,...,...,...
40104,43733,35,4.2,1,21,21,Windy,Jam,motorcycle,Metropolitian,Sports,16.600272
40105,43734,30,4.8,3,11,11,Windy,High,motorcycle,Metropolitian,Home,1.489846
40106,43736,30,4.9,4,23,0,Cloudy,Low,scooter,Metropolitian,Home,4.657195
40107,43737,20,4.7,0,13,13,Cloudy,High,motorcycle,Metropolitian,Kitchen,6.232393
40108,43738,23,4.9,2,17,17,Fog,Medium,scooter,Metropolitian,Cosmetics,12.074396

In [27]:
X

,Unnamed: 0,Agent_Age,Agent_Rating,Order_Date,Order_Time,Pickup_Time,Weather,Traffic,Vehicle,Area,Category,Distance_km
0,0,37,4.9,5,11,11,Sunny,High,motorcycle,Urban,Clothing,3.025149
1,1,34,4.5,4,19,19,Stormy,Jam,scooter,Metropolitian,Electronics,20.183530
2,2,23,4.4,5,8,8,Sandstorms,Low,motorcycle,Urban,Sports,1.552758
3,3,38,4.7,1,18,18,Sunny,Medium,motorcycle,Metropolitian,Cosmetics,7.790401
4,4,32,4.6,5,13,13,Cloudy,High,scooter,Metropolitian,Toys,6.210138
...,...,...,...,...,...,...,...,...,...,...,...,...
40104,43733,35,4.2,1,21,21,Windy,Jam,motorcycle,Metropolitian,Sports,16.600272
40105,43734,30,4.8,3,11,11,Windy,High,motorcycle,Metropolitian,Home,1.489846
40106,43736,30,4.9,4,23,0,Cloudy,Low,scooter,Metropolitian,Home,4.657195
40107,43737,20,4.7,0,13,13,Cloudy,High,motorcycle,Metropolitian,Kitchen,6.232393
40108,43738,23,4.9,2,17,17,Fog,Medium,scooter,Metropolitian,Cosmetics,12.074396